# Generated by Django 2.1.3 on 2018-11-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181130_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='direccion',
            field=models.CharField(default='Su casa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(default='Su casa', max_length=50),
            preserve_default=False,
        ),
    ]
